../pdb_v3_to_v2 AAAA.pdb > clean_aaaa.pdb
../pdb_v3_to_v2 AACA.pdb > clean_aaca.pdb
../pdb_v3_to_v2 AADA.pdb > clean_aada.pdb
../pdb_v3_to_v2 AAEA.pdb > clean_aaea.pdb
../pdb_v3_to_v2 AAFA.pdb > clean_aafa.pdb
../pdb_v3_to_v2 AAGA.pdb > clean_aaga.pdb
../pdb_v3_to_v2 AAHA.pdb > clean_aaha.pdb
../pdb_v3_to_v2 AAIA.pdb > clean_aaia.pdb
../pdb_v3_to_v2 AAKA.pdb > clean_aaka.pdb
../pdb_v3_to_v2 AALA.pdb > clean_aala.pdb
../pdb_v3_to_v2 AAMA.pdb > clean_aama.pdb
../pdb_v3_to_v2 AANA.pdb > clean_aana.pdb
../pdb_v3_to_v2 AAPA.pdb > clean_aapa.pdb
../pdb_v3_to_v2 AAQA.pdb > clean_aaqa.pdb
../pdb_v3_to_v2 AARA.pdb > clean_aara.pdb
../pdb_v3_to_v2 AASA.pdb > clean_aasa.pdb
../pdb_v3_to_v2 AATA.pdb > clean_aata.pdb
../pdb_v3_to_v2 AAVA.pdb > clean_aava.pdb
../pdb_v3_to_v2 AAWA.pdb > clean_aawa.pdb
../pdb_v3_to_v2 AAYA.pdb > clean_aaya.pdb
../pdb_v3_to_v2 ACAA.pdb > clean_acaa.pdb
../pdb_v3_to_v2 ACCA.pdb > clean_acca.pdb
../pdb_v3_to_v2 ACDA.pdb > clean_acda.pdb
../pdb_v3_to_v2 ACEA.pdb > clean_acea.pdb
../pdb_v3_to_v2 ACFA.pdb > clean_acfa.pdb
../pdb_v3_to_v2 ACGA.pdb > clean_acga.pdb
../pdb_v3_to_v2 ACHA.pdb > clean_acha.pdb
../pdb_v3_to_v2 ACIA.pdb > clean_acia.pdb
../pdb_v3_to_v2 ACKA.pdb > clean_acka.pdb
../pdb_v3_to_v2 ACLA.pdb > clean_acla.pdb
../pdb_v3_to_v2 ACMA.pdb > clean_acma.pdb
../pdb_v3_to_v2 ACNA.pdb > clean_acna.pdb
../pdb_v3_to_v2 ACPA.pdb > clean_acpa.pdb
../pdb_v3_to_v2 ACQA.pdb > clean_acqa.pdb
../pdb_v3_to_v2 ACRA.pdb > clean_acra.pdb
../pdb_v3_to_v2 ACSA.pdb > clean_acsa.pdb
../pdb_v3_to_v2 ACTA.pdb > clean_acta.pdb
../pdb_v3_to_v2 ACVA.pdb > clean_acva.pdb
../pdb_v3_to_v2 ACWA.pdb > clean_acwa.pdb
../pdb_v3_to_v2 ACYA.pdb > clean_acya.pdb
../pdb_v3_to_v2 ADAA.pdb > clean_adaa.pdb
../pdb_v3_to_v2 ADCA.pdb > clean_adca.pdb
../pdb_v3_to_v2 ADDA.pdb > clean_adda.pdb
../pdb_v3_to_v2 ADEA.pdb > clean_adea.pdb
../pdb_v3_to_v2 ADFA.pdb > clean_adfa.pdb
../pdb_v3_to_v2 ADGA.pdb > clean_adga.pdb
../pdb_v3_to_v2 ADHA.pdb > clean_adha.pdb
../pdb_v3_to_v2 ADIA.pdb > clean_adia.pdb
../pdb_v3_to_v2 ADKA.pdb > clean_adka.pdb
../pdb_v3_to_v2 ADLA.pdb > clean_adla.pdb
../pdb_v3_to_v2 ADMA.pdb > clean_adma.pdb
../pdb_v3_to_v2 ADNA.pdb > clean_adna.pdb
../pdb_v3_to_v2 ADPA.pdb > clean_adpa.pdb
../pdb_v3_to_v2 ADQA.pdb > clean_adqa.pdb
../pdb_v3_to_v2 ADRA.pdb > clean_adra.pdb
../pdb_v3_to_v2 ADSA.pdb > clean_adsa.pdb
../pdb_v3_to_v2 ADTA.pdb > clean_adta.pdb
../pdb_v3_to_v2 ADVA.pdb > clean_adva.pdb
../pdb_v3_to_v2 ADWA.pdb > clean_adwa.pdb
../pdb_v3_to_v2 ADYA.pdb > clean_adya.pdb
../pdb_v3_to_v2 AEAA.pdb > clean_aeaa.pdb
../pdb_v3_to_v2 AECA.pdb > clean_aeca.pdb
../pdb_v3_to_v2 AEDA.pdb > clean_aeda.pdb
../pdb_v3_to_v2 AEEA.pdb > clean_aeea.pdb
../pdb_v3_to_v2 AEFA.pdb > clean_aefa.pdb
../pdb_v3_to_v2 AEGA.pdb > clean_aega.pdb
../pdb_v3_to_v2 AEHA.pdb > clean_aeha.pdb
../pdb_v3_to_v2 AEIA.pdb > clean_aeia.pdb
../pdb_v3_to_v2 AEKA.pdb > clean_aeka.pdb
../pdb_v3_to_v2 AELA.pdb > clean_aela.pdb
../pdb_v3_to_v2 AEMA.pdb > clean_aema.pdb
../pdb_v3_to_v2 AENA.pdb > clean_aena.pdb
../pdb_v3_to_v2 AEPA.pdb > clean_aepa.pdb
../pdb_v3_to_v2 AEQA.pdb > clean_aeqa.pdb
../pdb_v3_to_v2 AERA.pdb > clean_aera.pdb
../pdb_v3_to_v2 AESA.pdb > clean_aesa.pdb
../pdb_v3_to_v2 AETA.pdb > clean_aeta.pdb
../pdb_v3_to_v2 AEVA.pdb > clean_aeva.pdb
../pdb_v3_to_v2 AEWA.pdb > clean_aewa.pdb
../pdb_v3_to_v2 AEYA.pdb > clean_aeya.pdb
../pdb_v3_to_v2 AFAA.pdb > clean_afaa.pdb
../pdb_v3_to_v2 AFCA.pdb > clean_afca.pdb
../pdb_v3_to_v2 AFDA.pdb > clean_afda.pdb
../pdb_v3_to_v2 AFEA.pdb > clean_afea.pdb
../pdb_v3_to_v2 AFFA.pdb > clean_affa.pdb
../pdb_v3_to_v2 AFGA.pdb > clean_afga.pdb
../pdb_v3_to_v2 AFHA.pdb > clean_afha.pdb
../pdb_v3_to_v2 AFIA.pdb > clean_afia.pdb
../pdb_v3_to_v2 AFKA.pdb > clean_afka.pdb
../pdb_v3_to_v2 AFLA.pdb > clean_afla.pdb
../pdb_v3_to_v2 AFMA.pdb > clean_afma.pdb
../pdb_v3_to_v2 AFNA.pdb > clean_afna.pdb
../pdb_v3_to_v2 AFPA.pdb > clean_afpa.pdb
../pdb_v3_to_v2 AFQA.pdb > clean_afqa.pdb
../pdb_v3_to_v2 AFRA.pdb > clean_afra.pdb
../pdb_v3_to_v2 AFSA.pdb > clean_afsa.pdb
../pdb_v3_to_v2 AFTA.pdb > clean_afta.pdb
../pdb_v3_to_v2 AFVA.pdb > clean_afva.pdb
../pdb_v3_to_v2 AFWA.pdb > clean_afwa.pdb
../pdb_v3_to_v2 AFYA.pdb > clean_afya.pdb
../pdb_v3_to_v2 AGAA.pdb > clean_agaa.pdb
../pdb_v3_to_v2 AGCA.pdb > clean_agca.pdb
../pdb_v3_to_v2 AGDA.pdb > clean_agda.pdb
../pdb_v3_to_v2 AGEA.pdb > clean_agea.pdb
../pdb_v3_to_v2 AGFA.pdb > clean_agfa.pdb
../pdb_v3_to_v2 AGGA.pdb > clean_agga.pdb
../pdb_v3_to_v2 AGHA.pdb > clean_agha.pdb
../pdb_v3_to_v2 AGIA.pdb > clean_agia.pdb
../pdb_v3_to_v2 AGKA.pdb > clean_agka.pdb
../pdb_v3_to_v2 AGLA.pdb > clean_agla.pdb
../pdb_v3_to_v2 AGMA.pdb > clean_agma.pdb
../pdb_v3_to_v2 AGNA.pdb > clean_agna.pdb
../pdb_v3_to_v2 AGPA.pdb > clean_agpa.pdb
../pdb_v3_to_v2 AGQA.pdb > clean_agqa.pdb
../pdb_v3_to_v2 AGRA.pdb > clean_agra.pdb
../pdb_v3_to_v2 AGSA.pdb > clean_agsa.pdb
../pdb_v3_to_v2 AGTA.pdb > clean_agta.pdb
../pdb_v3_to_v2 AGVA.pdb > clean_agva.pdb
../pdb_v3_to_v2 AGWA.pdb > clean_agwa.pdb
../pdb_v3_to_v2 AGYA.pdb > clean_agya.pdb
../pdb_v3_to_v2 AHAA.pdb > clean_ahaa.pdb
../pdb_v3_to_v2 AHCA.pdb > clean_ahca.pdb
../pdb_v3_to_v2 AHDA.pdb > clean_ahda.pdb
../pdb_v3_to_v2 AHEA.pdb > clean_ahea.pdb
../pdb_v3_to_v2 AHFA.pdb > clean_ahfa.pdb
../pdb_v3_to_v2 AHGA.pdb > clean_ahga.pdb
../pdb_v3_to_v2 AHHA.pdb > clean_ahha.pdb
../pdb_v3_to_v2 AHIA.pdb > clean_ahia.pdb
../pdb_v3_to_v2 AHKA.pdb > clean_ahka.pdb
../pdb_v3_to_v2 AHLA.pdb > clean_ahla.pdb
../pdb_v3_to_v2 AHMA.pdb > clean_ahma.pdb
../pdb_v3_to_v2 AHNA.pdb > clean_ahna.pdb
../pdb_v3_to_v2 AHPA.pdb > clean_ahpa.pdb
../pdb_v3_to_v2 AHQA.pdb > clean_ahqa.pdb
../pdb_v3_to_v2 AHRA.pdb > clean_ahra.pdb
../pdb_v3_to_v2 AHSA.pdb > clean_ahsa.pdb
../pdb_v3_to_v2 AHTA.pdb > clean_ahta.pdb
../pdb_v3_to_v2 AHVA.pdb > clean_ahva.pdb
../pdb_v3_to_v2 AHWA.pdb > clean_ahwa.pdb
../pdb_v3_to_v2 AHYA.pdb > clean_ahya.pdb
../pdb_v3_to_v2 AIAA.pdb > clean_aiaa.pdb
../pdb_v3_to_v2 AICA.pdb > clean_aica.pdb
../pdb_v3_to_v2 AIDA.pdb > clean_aida.pdb
../pdb_v3_to_v2 AIEA.pdb > clean_aiea.pdb
../pdb_v3_to_v2 AIFA.pdb > clean_aifa.pdb
../pdb_v3_to_v2 AIGA.pdb > clean_aiga.pdb
../pdb_v3_to_v2 AIHA.pdb > clean_aiha.pdb
../pdb_v3_to_v2 AIIA.pdb > clean_aiia.pdb
../pdb_v3_to_v2 AIKA.pdb > clean_aika.pdb
../pdb_v3_to_v2 AILA.pdb > clean_aila.pdb
../pdb_v3_to_v2 AIMA.pdb > clean_aima.pdb
../pdb_v3_to_v2 AINA.pdb > clean_aina.pdb
../pdb_v3_to_v2 AIPA.pdb > clean_aipa.pdb
../pdb_v3_to_v2 AIQA.pdb > clean_aiqa.pdb
../pdb_v3_to_v2 AIRA.pdb > clean_aira.pdb
../pdb_v3_to_v2 AISA.pdb > clean_aisa.pdb
../pdb_v3_to_v2 AITA.pdb > clean_aita.pdb
../pdb_v3_to_v2 AIVA.pdb > clean_aiva.pdb
../pdb_v3_to_v2 AIWA.pdb > clean_aiwa.pdb
../pdb_v3_to_v2 AIYA.pdb > clean_aiya.pdb
../pdb_v3_to_v2 AKAA.pdb > clean_akaa.pdb
../pdb_v3_to_v2 AKCA.pdb > clean_akca.pdb
../pdb_v3_to_v2 AKDA.pdb > clean_akda.pdb
../pdb_v3_to_v2 AKEA.pdb > clean_akea.pdb
../pdb_v3_to_v2 AKFA.pdb > clean_akfa.pdb
../pdb_v3_to_v2 AKGA.pdb > clean_akga.pdb
../pdb_v3_to_v2 AKHA.pdb > clean_akha.pdb
../pdb_v3_to_v2 AKIA.pdb > clean_akia.pdb
../pdb_v3_to_v2 AKKA.pdb > clean_akka.pdb
../pdb_v3_to_v2 AKLA.pdb > clean_akla.pdb
../pdb_v3_to_v2 AKMA.pdb > clean_akma.pdb
../pdb_v3_to_v2 AKNA.pdb > clean_akna.pdb
../pdb_v3_to_v2 AKPA.pdb > clean_akpa.pdb
../pdb_v3_to_v2 AKQA.pdb > clean_akqa.pdb
../pdb_v3_to_v2 AKRA.pdb > clean_akra.pdb
../pdb_v3_to_v2 AKSA.pdb > clean_aksa.pdb
../pdb_v3_to_v2 AKTA.pdb > clean_akta.pdb
../pdb_v3_to_v2 AKVA.pdb > clean_akva.pdb
../pdb_v3_to_v2 AKWA.pdb > clean_akwa.pdb
../pdb_v3_to_v2 AKYA.pdb > clean_akya.pdb
../pdb_v3_to_v2 ALAA.pdb > clean_alaa.pdb
../pdb_v3_to_v2 ALCA.pdb > clean_alca.pdb
../pdb_v3_to_v2 ALDA.pdb > clean_alda.pdb
../pdb_v3_to_v2 ALEA.pdb > clean_alea.pdb
../pdb_v3_to_v2 ALFA.pdb > clean_alfa.pdb
../pdb_v3_to_v2 ALGA.pdb > clean_alga.pdb
../pdb_v3_to_v2 ALHA.pdb > clean_alha.pdb
../pdb_v3_to_v2 ALIA.pdb > clean_alia.pdb
../pdb_v3_to_v2 ALKA.pdb > clean_alka.pdb
../pdb_v3_to_v2 ALLA.pdb > clean_alla.pdb
../pdb_v3_to_v2 ALMA.pdb > clean_alma.pdb
../pdb_v3_to_v2 ALNA.pdb > clean_alna.pdb
../pdb_v3_to_v2 ALPA.pdb > clean_alpa.pdb
../pdb_v3_to_v2 ALQA.pdb > clean_alqa.pdb
../pdb_v3_to_v2 ALRA.pdb > clean_alra.pdb
../pdb_v3_to_v2 ALSA.pdb > clean_alsa.pdb
../pdb_v3_to_v2 ALTA.pdb > clean_alta.pdb
../pdb_v3_to_v2 ALVA.pdb > clean_alva.pdb
../pdb_v3_to_v2 ALWA.pdb > clean_alwa.pdb
../pdb_v3_to_v2 ALYA.pdb > clean_alya.pdb
../pdb_v3_to_v2 AMAA.pdb > clean_amaa.pdb
../pdb_v3_to_v2 AMCA.pdb > clean_amca.pdb
../pdb_v3_to_v2 AMDA.pdb > clean_amda.pdb
../pdb_v3_to_v2 AMEA.pdb > clean_amea.pdb
../pdb_v3_to_v2 AMFA.pdb > clean_amfa.pdb
../pdb_v3_to_v2 AMGA.pdb > clean_amga.pdb
../pdb_v3_to_v2 AMHA.pdb > clean_amha.pdb
../pdb_v3_to_v2 AMIA.pdb > clean_amia.pdb
../pdb_v3_to_v2 AMKA.pdb > clean_amka.pdb
../pdb_v3_to_v2 AMLA.pdb > clean_amla.pdb
../pdb_v3_to_v2 AMMA.pdb > clean_amma.pdb
../pdb_v3_to_v2 AMNA.pdb > clean_amna.pdb
../pdb_v3_to_v2 AMPA.pdb > clean_ampa.pdb
../pdb_v3_to_v2 AMQA.pdb > clean_amqa.pdb
../pdb_v3_to_v2 AMRA.pdb > clean_amra.pdb
../pdb_v3_to_v2 AMSA.pdb > clean_amsa.pdb
../pdb_v3_to_v2 AMTA.pdb > clean_amta.pdb
../pdb_v3_to_v2 AMVA.pdb > clean_amva.pdb
../pdb_v3_to_v2 AMWA.pdb > clean_amwa.pdb
../pdb_v3_to_v2 AMYA.pdb > clean_amya.pdb
../pdb_v3_to_v2 ANAA.pdb > clean_anaa.pdb
../pdb_v3_to_v2 ANCA.pdb > clean_anca.pdb
../pdb_v3_to_v2 ANDA.pdb > clean_anda.pdb
../pdb_v3_to_v2 ANEA.pdb > clean_anea.pdb
../pdb_v3_to_v2 ANFA.pdb > clean_anfa.pdb
../pdb_v3_to_v2 ANGA.pdb > clean_anga.pdb
../pdb_v3_to_v2 ANHA.pdb > clean_anha.pdb
../pdb_v3_to_v2 ANIA.pdb > clean_ania.pdb
../pdb_v3_to_v2 ANKA.pdb > clean_anka.pdb
../pdb_v3_to_v2 ANLA.pdb > clean_anla.pdb
../pdb_v3_to_v2 ANMA.pdb > clean_anma.pdb
../pdb_v3_to_v2 ANNA.pdb > clean_anna.pdb
../pdb_v3_to_v2 ANPA.pdb > clean_anpa.pdb
../pdb_v3_to_v2 ANQA.pdb > clean_anqa.pdb
../pdb_v3_to_v2 ANRA.pdb > clean_anra.pdb
../pdb_v3_to_v2 ANSA.pdb > clean_ansa.pdb
../pdb_v3_to_v2 ANTA.pdb > clean_anta.pdb
../pdb_v3_to_v2 ANVA.pdb > clean_anva.pdb
../pdb_v3_to_v2 ANWA.pdb > clean_anwa.pdb
../pdb_v3_to_v2 ANYA.pdb > clean_anya.pdb
../pdb_v3_to_v2 APAA.pdb > clean_apaa.pdb
../pdb_v3_to_v2 APCA.pdb > clean_apca.pdb
../pdb_v3_to_v2 APDA.pdb > clean_apda.pdb
../pdb_v3_to_v2 APEA.pdb > clean_apea.pdb
../pdb_v3_to_v2 APFA.pdb > clean_apfa.pdb
../pdb_v3_to_v2 APGA.pdb > clean_apga.pdb
../pdb_v3_to_v2 APHA.pdb > clean_apha.pdb
../pdb_v3_to_v2 APIA.pdb > clean_apia.pdb
../pdb_v3_to_v2 APKA.pdb > clean_apka.pdb
../pdb_v3_to_v2 APLA.pdb > clean_apla.pdb
../pdb_v3_to_v2 APMA.pdb > clean_apma.pdb
../pdb_v3_to_v2 APNA.pdb > clean_apna.pdb
../pdb_v3_to_v2 APPA.pdb > clean_appa.pdb
../pdb_v3_to_v2 APQA.pdb > clean_apqa.pdb
../pdb_v3_to_v2 APRA.pdb > clean_apra.pdb
../pdb_v3_to_v2 APSA.pdb > clean_apsa.pdb
../pdb_v3_to_v2 APTA.pdb > clean_apta.pdb
../pdb_v3_to_v2 APVA.pdb > clean_apva.pdb
../pdb_v3_to_v2 APWA.pdb > clean_apwa.pdb
../pdb_v3_to_v2 APYA.pdb > clean_apya.pdb
../pdb_v3_to_v2 AQAA.pdb > clean_aqaa.pdb
../pdb_v3_to_v2 AQCA.pdb > clean_aqca.pdb
../pdb_v3_to_v2 AQDA.pdb > clean_aqda.pdb
../pdb_v3_to_v2 AQEA.pdb > clean_aqea.pdb
../pdb_v3_to_v2 AQFA.pdb > clean_aqfa.pdb
../pdb_v3_to_v2 AQGA.pdb > clean_aqga.pdb
../pdb_v3_to_v2 AQHA.pdb > clean_aqha.pdb
../pdb_v3_to_v2 AQIA.pdb > clean_aqia.pdb
../pdb_v3_to_v2 AQKA.pdb > clean_aqka.pdb
../pdb_v3_to_v2 AQLA.pdb > clean_aqla.pdb
../pdb_v3_to_v2 AQMA.pdb > clean_aqma.pdb
../pdb_v3_to_v2 AQNA.pdb > clean_aqna.pdb
../pdb_v3_to_v2 AQPA.pdb > clean_aqpa.pdb
../pdb_v3_to_v2 AQQA.pdb > clean_aqqa.pdb
../pdb_v3_to_v2 AQRA.pdb > clean_aqra.pdb
../pdb_v3_to_v2 AQSA.pdb > clean_aqsa.pdb
../pdb_v3_to_v2 AQTA.pdb > clean_aqta.pdb
../pdb_v3_to_v2 AQVA.pdb > clean_aqva.pdb
../pdb_v3_to_v2 AQWA.pdb > clean_aqwa.pdb
../pdb_v3_to_v2 AQYA.pdb > clean_aqya.pdb
../pdb_v3_to_v2 ARAA.pdb > clean_araa.pdb
../pdb_v3_to_v2 ARCA.pdb > clean_arca.pdb
../pdb_v3_to_v2 ARDA.pdb > clean_arda.pdb
../pdb_v3_to_v2 AREA.pdb > clean_area.pdb
../pdb_v3_to_v2 ARFA.pdb > clean_arfa.pdb
../pdb_v3_to_v2 ARGA.pdb > clean_arga.pdb
../pdb_v3_to_v2 ARHA.pdb > clean_arha.pdb
../pdb_v3_to_v2 ARIA.pdb > clean_aria.pdb
../pdb_v3_to_v2 ARKA.pdb > clean_arka.pdb
../pdb_v3_to_v2 ARLA.pdb > clean_arla.pdb
../pdb_v3_to_v2 ARMA.pdb > clean_arma.pdb
../pdb_v3_to_v2 ARNA.pdb > clean_arna.pdb
../pdb_v3_to_v2 ARPA.pdb > clean_arpa.pdb
../pdb_v3_to_v2 ARQA.pdb > clean_arqa.pdb
../pdb_v3_to_v2 ARRA.pdb > clean_arra.pdb
../pdb_v3_to_v2 ARSA.pdb > clean_arsa.pdb
../pdb_v3_to_v2 ARTA.pdb > clean_arta.pdb
../pdb_v3_to_v2 ARVA.pdb > clean_arva.pdb
../pdb_v3_to_v2 ARWA.pdb > clean_arwa.pdb
../pdb_v3_to_v2 ARYA.pdb > clean_arya.pdb
../pdb_v3_to_v2 ASAA.pdb > clean_asaa.pdb
../pdb_v3_to_v2 ASCA.pdb > clean_asca.pdb
../pdb_v3_to_v2 ASDA.pdb > clean_asda.pdb
../pdb_v3_to_v2 ASEA.pdb > clean_asea.pdb
../pdb_v3_to_v2 ASFA.pdb > clean_asfa.pdb
../pdb_v3_to_v2 ASGA.pdb > clean_asga.pdb
../pdb_v3_to_v2 ASHA.pdb > clean_asha.pdb
../pdb_v3_to_v2 ASIA.pdb > clean_asia.pdb
../pdb_v3_to_v2 ASKA.pdb > clean_aska.pdb
../pdb_v3_to_v2 ASLA.pdb > clean_asla.pdb
../pdb_v3_to_v2 ASMA.pdb > clean_asma.pdb
../pdb_v3_to_v2 ASNA.pdb > clean_asna.pdb
../pdb_v3_to_v2 ASPA.pdb > clean_aspa.pdb
../pdb_v3_to_v2 ASQA.pdb > clean_asqa.pdb
../pdb_v3_to_v2 ASRA.pdb > clean_asra.pdb
../pdb_v3_to_v2 ASSA.pdb > clean_assa.pdb
../pdb_v3_to_v2 ASTA.pdb > clean_asta.pdb
../pdb_v3_to_v2 ASVA.pdb > clean_asva.pdb
../pdb_v3_to_v2 ASWA.pdb > clean_aswa.pdb
../pdb_v3_to_v2 ASYA.pdb > clean_asya.pdb
../pdb_v3_to_v2 ATAA.pdb > clean_ataa.pdb
../pdb_v3_to_v2 ATCA.pdb > clean_atca.pdb
../pdb_v3_to_v2 ATDA.pdb > clean_atda.pdb
../pdb_v3_to_v2 ATEA.pdb > clean_atea.pdb
../pdb_v3_to_v2 ATFA.pdb > clean_atfa.pdb
../pdb_v3_to_v2 ATGA.pdb > clean_atga.pdb
../pdb_v3_to_v2 ATHA.pdb > clean_atha.pdb
../pdb_v3_to_v2 ATIA.pdb > clean_atia.pdb
../pdb_v3_to_v2 ATKA.pdb > clean_atka.pdb
../pdb_v3_to_v2 ATLA.pdb > clean_atla.pdb
../pdb_v3_to_v2 ATMA.pdb > clean_atma.pdb
../pdb_v3_to_v2 ATNA.pdb > clean_atna.pdb
../pdb_v3_to_v2 ATPA.pdb > clean_atpa.pdb
../pdb_v3_to_v2 ATQA.pdb > clean_atqa.pdb
../pdb_v3_to_v2 ATRA.pdb > clean_atra.pdb
../pdb_v3_to_v2 ATSA.pdb > clean_atsa.pdb
../pdb_v3_to_v2 ATTA.pdb > clean_atta.pdb
../pdb_v3_to_v2 ATVA.pdb > clean_atva.pdb
../pdb_v3_to_v2 ATWA.pdb > clean_atwa.pdb
../pdb_v3_to_v2 ATYA.pdb > clean_atya.pdb
../pdb_v3_to_v2 AVAA.pdb > clean_avaa.pdb
../pdb_v3_to_v2 AVCA.pdb > clean_avca.pdb
../pdb_v3_to_v2 AVDA.pdb > clean_avda.pdb
../pdb_v3_to_v2 AVEA.pdb > clean_avea.pdb
../pdb_v3_to_v2 AVFA.pdb > clean_avfa.pdb
../pdb_v3_to_v2 AVGA.pdb > clean_avga.pdb
../pdb_v3_to_v2 AVHA.pdb > clean_avha.pdb
../pdb_v3_to_v2 AVIA.pdb > clean_avia.pdb
../pdb_v3_to_v2 AVKA.pdb > clean_avka.pdb
../pdb_v3_to_v2 AVLA.pdb > clean_avla.pdb
../pdb_v3_to_v2 AVMA.pdb > clean_avma.pdb
../pdb_v3_to_v2 AVNA.pdb > clean_avna.pdb
../pdb_v3_to_v2 AVPA.pdb > clean_avpa.pdb
../pdb_v3_to_v2 AVQA.pdb > clean_avqa.pdb
../pdb_v3_to_v2 AVRA.pdb > clean_avra.pdb
../pdb_v3_to_v2 AVSA.pdb > clean_avsa.pdb
../pdb_v3_to_v2 AVTA.pdb > clean_avta.pdb
../pdb_v3_to_v2 AVVA.pdb > clean_avva.pdb
../pdb_v3_to_v2 AVWA.pdb > clean_avwa.pdb
../pdb_v3_to_v2 AVYA.pdb > clean_avya.pdb
../pdb_v3_to_v2 AWAA.pdb > clean_awaa.pdb
../pdb_v3_to_v2 AWCA.pdb > clean_awca.pdb
../pdb_v3_to_v2 AWDA.pdb > clean_awda.pdb
../pdb_v3_to_v2 AWEA.pdb > clean_awea.pdb
../pdb_v3_to_v2 AWFA.pdb > clean_awfa.pdb
../pdb_v3_to_v2 AWGA.pdb > clean_awga.pdb
../pdb_v3_to_v2 AWHA.pdb > clean_awha.pdb
../pdb_v3_to_v2 AWIA.pdb > clean_awia.pdb
../pdb_v3_to_v2 AWKA.pdb > clean_awka.pdb
../pdb_v3_to_v2 AWLA.pdb > clean_awla.pdb
../pdb_v3_to_v2 AWMA.pdb > clean_awma.pdb
../pdb_v3_to_v2 AWNA.pdb > clean_awna.pdb
../pdb_v3_to_v2 AWPA.pdb > clean_awpa.pdb
../pdb_v3_to_v2 AWQA.pdb > clean_awqa.pdb
../pdb_v3_to_v2 AWRA.pdb > clean_awra.pdb
../pdb_v3_to_v2 AWSA.pdb > clean_awsa.pdb
../pdb_v3_to_v2 AWTA.pdb > clean_awta.pdb
../pdb_v3_to_v2 AWVA.pdb > clean_awva.pdb
../pdb_v3_to_v2 AWWA.pdb > clean_awwa.pdb
../pdb_v3_to_v2 AWYA.pdb > clean_awya.pdb
../pdb_v3_to_v2 AYAA.pdb > clean_ayaa.pdb
../pdb_v3_to_v2 AYCA.pdb > clean_ayca.pdb
../pdb_v3_to_v2 AYDA.pdb > clean_ayda.pdb
../pdb_v3_to_v2 AYEA.pdb > clean_ayea.pdb
../pdb_v3_to_v2 AYFA.pdb > clean_ayfa.pdb
../pdb_v3_to_v2 AYGA.pdb > clean_ayga.pdb
../pdb_v3_to_v2 AYHA.pdb > clean_ayha.pdb
../pdb_v3_to_v2 AYIA.pdb > clean_ayia.pdb
../pdb_v3_to_v2 AYKA.pdb > clean_ayka.pdb
../pdb_v3_to_v2 AYLA.pdb > clean_ayla.pdb
../pdb_v3_to_v2 AYMA.pdb > clean_ayma.pdb
../pdb_v3_to_v2 AYNA.pdb > clean_ayna.pdb
../pdb_v3_to_v2 AYPA.pdb > clean_aypa.pdb
../pdb_v3_to_v2 AYQA.pdb > clean_ayqa.pdb
../pdb_v3_to_v2 AYRA.pdb > clean_ayra.pdb
../pdb_v3_to_v2 AYSA.pdb > clean_aysa.pdb
../pdb_v3_to_v2 AYTA.pdb > clean_ayta.pdb
../pdb_v3_to_v2 AYVA.pdb > clean_ayva.pdb
../pdb_v3_to_v2 AYWA.pdb > clean_aywa.pdb
../pdb_v3_to_v2 AYYA.pdb > clean_ayya.pdb
